development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kmp_development
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: kmp_production
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

